- hosts: localhost
  tasks:
    - name: Include macOS specific tasks
      include_tasks: macos/macos.yaml
      when: ansible_os_family == "Darwin"
      tags:
        - core

    - name: Include linux specific tasks
      include_tasks: debian/debian.yaml
      when: ansible_os_family == "Debian"
      tags:
        - core

    - name: Include Windows specific tasks
      include_tasks: windows/windows.yaml
      when: ansible_os_family == "Windows"
      tags:
        - core